### PR TITLE
Override finder fix non template

### PR DESCRIPTION
**Pull request by swaschkut**

### CODE REVIEW

**Comment by cfrank18** [comment]
With Migration tool is it possible to extract data form .xml file them send that file to excel? Form example I have file called  test123.xml I want  use pan-configuratir so I can export that amp file to excel. Is that possible? O rona I use pan-configuration to filter on xml file so I can see what rules have  service “of any”?

 I do nto have right to box to generate API key buy wondering if config will work?
*************************************************************************
This e-mail may contain confidential or privileged information.
If you are not the intended recipient, please notify the sender immediately and then delete it.

TIAA
*************************************************************************

**Comment by swaschkut** [comment]
pa_rule-edit in=test123.xml out=/dev/null actions=exporttoexcel:rules_any.xml 'filter=(service is.any)'

**Comment by cfrank18** [comment]
When running address-merger.php or service-merger.php how do we resovle  issue with “backtrace errors” that show up




*************************************************************************
This e-mail may contain confidential or privileged information.
If you are not the intended recipient, please notify the sender immediately and then delete it.

TIAA
*************************************************************************

**Comment by cpainchaud** [comment]
You need to read the error message and provide it to us

**Pull request merged**
