### PR TITLE
Address merger introduce dupalgorithm

### PR DESCRIPTION
**Pull request by swaschkut**

### CODE REVIEW

**Comment by swaschkut** [comment]
unused object can be found with another util:
pa_address-edit in=api://192.168.55.202 actions=display 'filter=(refcount = 0)'

duplicate values can be found best with pa_address-merger against an offline file:
pa_address-merger in=[INPUT-CONFIG] out=[OUTPUTCONFIG] location=[LOCATION]

**Comment by cfrank18** [comment]
Can you confirm syntax? I get a error when I do refcount=0



ash-3.2$ php  address-edit.php  in=api://10.x.x.x  actions=display "filter=(refcount=1)" location=any


***********************************************

*********** ADDRESS-EDIT UTILITY **************



 - Downloading config from API... OK!

 - Detected platform type is 'panorama'



**ERROR** Rule filter parser: unsupported field name 'refcount=1' in expression 'refcount=1'

**Comment by swaschkut** [comment]
Please use:
php address-edit.php in=api://10.x.x.x actions=display 'filter=(refcount = 1)' location=any

as mentioned in my comment " = " is definitive needed. (blank before and after the equal)

**Comment by cfrank18** [comment]
Thanks worked.

**Comment by cfrank18** [comment]
With rhis command . How a n I just view them the duplicate versus doing the actual merger


duplicate values can be found best with pa_address-merger against an offline file:
pa_address-merger in=[INPUT-CONFIG] out=[OUTPUTCONFIG] location=[LOCATION]

**Pull request merged**
